defaults:
  # name of a file in the config/live directory
  # or an absolute path to a config file
  # aliases: cfg
  config: latest.json

  # following settings are ignored if set to 0
  # aliases: lw, lwe
  long_exposure: 0
  # aliases: sw, swe
  short_exposure: 0
  # aliases: ab
  assigned_balance: 0

  # modes info: https://www.passivbot.com/en/latest/live/#controlling-the-bot
  # aliases: lm
  long_mode: n

  # aliases: sm
  short_mode: m

  # futures or spot
  # default is futures
  market_type: futures

# it is highly recommended to read the docs/manager.md
# for the advanced instances configuration
instances:
  - user: binance_0x
    symbols:
      - BTCUSDT
      - ETHUSDT
